# Основные настройки
title: "Заметки"
author: "Николай Мишонин"

# Настройки Jekyll
markdown: kramdown
highlighter: rouge
permalink: /:year/:month/:day/:title/

# Плагины
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Настройки GitHub Pages
github:
  is_project_page: false

# Настройки постов
posts:
  layout: post
  title: true
  date: true
  author: true
  comments: false
  share: true
  read_time: true

# Настройки страниц
pages:
  layout: page
  title: true
  date: false
  author: false
  comments: false
  share: false
  read_time: false
